program Project1;

uses
  System.StartUpCopy,
  FMX.Forms,
  FHIR.FMX.Ctrls in 'C:\Components\FHIR.FMX.Ctrls.pas',
  FHIR.Tools.Client in '..\server\fhirserver\reference-platform\client\FHIR.Tools.Client.pas',
  FHIR.Support.Strings in '..\server\fhirserver\reference-platform\support\FHIR.Support.Strings.pas',
  FHIR.Support.Math in '..\server\fhirserver\reference-platform\support\FHIR.Support.Math.pas',
  FHIR.Support.Osx in '..\server\fhirserver\reference-platform\support\FHIR.Support.Osx.pas',
  FHIR.Support.Decimal in '..\server\fhirserver\reference-platform\support\FHIR.Support.Decimal.pas',
  FHIR.Support.DateTime in '..\server\fhirserver\reference-platform\support\FHIR.Support.DateTime.pas',
  FHIR.Support.Mime in '..\server\fhirserver\reference-platform\support\FHIR.Support.Mime.pas',
  FHIR.Support.Objects in '..\server\fhirserver\reference-platform\support\FHIR.Support.Objects.pas',
  FHIR.Support.Exceptions in '..\server\fhirserver\reference-platform\support\FHIR.Support.Exceptions.pas',
  FHIR.Support.Generics in '..\server\fhirserver\reference-platform\support\FHIR.Support.Generics.pas',
  FHIR.Support.Stream in '..\server\fhirserver\reference-platform\support\FHIR.Support.Stream.pas',
  FHIR.Support.Collections in '..\server\fhirserver\reference-platform\support\FHIR.Support.Collections.pas',
  FHIR.Support.Binary in '..\server\fhirserver\reference-platform\support\FHIR.Support.Binary.pas',
  FHIR.Support.System in '..\server\fhirserver\reference-platform\support\FHIR.Support.System.pas',
  FHIR.Support.Json in '..\server\fhirserver\reference-platform\support\FHIR.Support.Json.pas',
  FHIR.Tools.Parser in '..\server\fhirserver\reference-platform\tools\FHIR.Tools.Parser.pas',
  FHIR.R4.Xml in '..\server\fhirserver\reference-platform\r4\FHIR.R4.Xml.pas',
  FHIR.Base.Parser in '..\server\fhirserver\reference-platform\base\FHIR.Base.Parser.pas',
  FHIR.Support.MXml in '..\server\fhirserver\reference-platform\support\FHIR.Support.MXml.pas',
  FHIR.Support.Turtle in '..\server\fhirserver\reference-platform\support\FHIR.Support.Turtle.pas',
  FHIR.Base.Objects in '..\server\fhirserver\reference-platform\base\FHIR.Base.Objects.pas',
  FHIR.Base.Utilities in '..\server\fhirserver\reference-platform\base\FHIR.Base.Utilities.pas',
  FHIR.R4.Utilities in '..\server\fhirserver\reference-platform\r4\FHIR.R4.Utilities.pas',
  FHIR.Web.Parsers in '..\server\fhirserver\reference-platform\support\FHIR.Web.Parsers.pas',
  FHIR.Web.Fetcher in '..\server\fhirserver\reference-platform\support\FHIR.Web.Fetcher.pas',
  FHIR.R4.Context in '..\server\fhirserver\reference-platform\r4\FHIR.R4.Context.pas',
  FHIR.R4.Types in '..\server\fhirserver\reference-platform\r4\FHIR.R4.Types.pas',
  FHIR.R4.Resources in '..\server\fhirserver\reference-platform\r4\FHIR.R4.Resources.pas',
  FHIR.Tools.Session in '..\server\fhirserver\reference-platform\tools\FHIR.Tools.Session.pas',
  FHIR.Base.Scim in '..\server\fhirserver\reference-platform\base\FHIR.Base.Scim.pas',
  FHIR.R4.Constants in '..\server\fhirserver\reference-platform\r4\FHIR.R4.Constants.pas',
  FHIR.Tools.Security in '..\server\fhirserver\reference-platform\tools\FHIR.Tools.Security.pas',
  FHIR.R4.Tags in '..\server\fhirserver\reference-platform\r4\FHIR.R4.Tags.pas',
  FHIR.Base.Lang in '..\server\fhirserver\reference-platform\base\FHIR.Base.Lang.pas',
  FHIR.Base.Xhtml in '..\server\fhirserver\reference-platform\base\FHIR.Base.Xhtml.pas',
  FHIR.R4.Json in '..\server\fhirserver\reference-platform\r4\FHIR.R4.Json.pas',
  FHIR.R4.Turtle in '..\server\fhirserver\reference-platform\r4\FHIR.R4.Turtle.pas',
  FHIR.R4.ElementModel in '..\server\fhirserver\reference-platform\r4\FHIR.R4.ElementModel.pas',
  FHIR.R4.Profiles in '..\server\fhirserver\reference-platform\r4\FHIR.R4.Profiles.pas',
  FHIR.Support.Lock in '..\server\fhirserver\reference-platform\support\FHIR.Support.Lock.pas',
  FHIR.R4.PathEngine in '..\server\fhirserver\reference-platform\r4\FHIR.R4.PathEngine.pas',
//  FHIR.Client.SmartUtilities in '..\server\fhirserver\reference-platform\client\FHIR.Client.SmartUtilities.pas',
  FHIR.CdsHooks.Utilities in '..\server\fhirserver\reference-platform\support\FHIR.CdsHooks.Utilities.pas',
  FastMM4Messages in '..\server\fhirserver\Libraries\FMM\FastMM4Messages.pas',
//  OrganizationChooser in 'OrganizationChooser.pas' {OrganizationSelectionForm},
//  FHIRToolkitForm in 'FHIRToolkitForm.pas' {MasterToolsForm},
  FHIR.R4.IndexInfo in '..\server\fhirserver\reference-platform\r4\FHIR.R4.IndexInfo.pas',
  FHIR.Tools.Indexing in '..\server\fhirserver\reference-platform\tools\FHIR.Tools.Indexing.pas',
  FHIR.Tools.DiffEngine in '..\server\fhirserver\reference-platform\tools\FHIR.Tools.DiffEngine.pas',
  FHIR.Client.Registry in '..\server\fhirserver\reference-platform\client\FHIR.Client.Registry.pas',
  FHIR.Client.ServerDialogFMX in '..\server\fhirserver\reference-platform\client\FHIR.Client.ServerDialogFMX.pas' {EditRegisteredServerForm},
  FHIR.Web.HtmlGen in '..\server\fhirserver\reference-platform\Support\FHIR.Web.HtmlGen.pas',
  FHIR.Client.ClientDialogFMX in '..\server\fhirserver\reference-platform\client\FHIR.Client.ClientDialogFMX.pas' {RegisterClientForm},
//  FHIR.Ui.ComboFMX in '..\server\fhirserver\reference-platform\client\FHIR.Ui.ComboFMX.pas',
  FHIR.Support.Signatures in '..\server\fhirserver\reference-platform\support\FHIR.Support.Signatures.pas',
  FHIR.Ucum.IFace in '..\server\fhirserver\reference-platform\support\FHIR.Ucum.IFace.pas',
  FHIR.R4.PathNode in '..\server\fhirserver\reference-platform\r4\FHIR.R4.PathNode.pas',
  FHIR.Debug.Logging in '..\server\fhirserver\reference-platform\support\FHIR.Debug.Logging.pas',
  FHIR.R4.Questionnaire2 in '..\server\fhirserver\reference-platform\r4\FHIR.R4.Questionnaire2.pas',
  FHIR.R4.Base in '..\server\fhirserver\reference-platform\r4\FHIR.R4.Base.pas',
  FHIR.R4.ParserBase in '..\server\fhirserver\reference-platform\r4\FHIR.R4.ParserBase.pas',
  FHIR.Tools.XhtmlComp in '..\server\fhirserver\reference-platform\tools\FHIR.Tools.XhtmlComp.pas',
  FHIR.R4.Parser in '..\server\fhirserver\reference-platform\r4\FHIR.R4.Parser.pas',
  FHIR.Client.Base in '..\server\fhirserver\reference-platform\client\FHIR.Client.Base.pas',
  FHIR.Client.HTTP in '..\server\fhirserver\reference-platform\client\FHIR.Client.HTTP.pas',
  FHIR.Client.Threaded in '..\server\fhirserver\reference-platform\client\FHIR.Client.Threaded.pas',
  FHIR.R4.Client in '..\server\fhirserver\reference-platform\r4\FHIR.R4.Client.pas',
  FHIR.Support.Text in '..\server\fhirserver\reference-platform\support\FHIR.Support.Text.pas',
  FHIR.Support.Xml in '..\server\fhirserver\reference-platform\support\FHIR.Support.Xml.pas',
  FHIR.Support.Zip in '..\server\fhirserver\reference-platform\support\FHIR.Support.Zip.pas',
  FHIR.Support.WInInet in '..\server\fhirserver\reference-platform\support\FHIR.Support.WInInet.pas',
  FHIR.Support.Controllers in '..\server\fhirserver\reference-platform\support\FHIR.Support.Controllers.pas',
  FHIR.Support.Certs in '..\server\fhirserver\reference-platform\support\FHIR.Support.Certs.pas',
  FHIR.Misc.GraphQL in '..\server\fhirserver\reference-platform\support\FHIR.Misc.GraphQL.pas',
  FHIR.Base.Factory in '..\server\fhirserver\reference-platform\base\FHIR.Base.Factory.pas',
  FHIR.Base.Validator in '..\server\fhirserver\reference-platform\base\FHIR.Base.Validator.pas',
  FHIR.XVersion.Resources in '..\server\fhirserver\reference-platform\xversion\FHIR.XVersion.Resources.pas',
  FHIR.Base.Narrative in '..\server\fhirserver\reference-platform\base\FHIR.Base.Narrative.pas',
  FHIR.Base.PathEngine in '..\server\fhirserver\reference-platform\base\FHIR.Base.PathEngine.pas',
  FHIR.R4.Common in '..\server\fhirserver\reference-platform\r4\FHIR.R4.Common.pas',
  FHIR.R4.Factory in '..\server\fhirserver\reference-platform\r4\FHIR.R4.Factory.pas',
  FHIR.R4.Narrative in '..\server\fhirserver\reference-platform\r4\FHIR.R4.Narrative.pas',
  FHIR.R4.Validator in '..\server\fhirserver\reference-platform\r4\FHIR.R4.Validator.pas',
  FHIR.Client.Async in '..\server\fhirserver\reference-platform\client\FHIR.Client.Async.pas',
  FHIR.Cache.PackageManager in '..\server\fhirserver\reference-platform\cache\FHIR.Cache.PackageManager.pas',
  FHIR.Support.Tarball in '..\server\fhirserver\reference-platform\support\FHIR.Support.Tarball.pas',
  FHIR.Support.Shell in '..\server\fhirserver\reference-platform\support\FHIR.Support.Shell.pas',
  FHIR.Tools.ValidationWrapper in '..\server\fhirserver\reference-platform\tools\FHIR.Tools.ValidationWrapper.pas',

  Unit1 in 'Unit1.pas' {Form1};

{$R *.res}

begin
  Application.Initialize;
  Application.CreateForm(TForm1, Form1);
  Application.Run;
end.
